# Enabling debug mode will send extra messages in the console log to help debug the plugin.
debug: false

# Number of quests that can be in progress at a time.
# This value is ignored and only 1 quest can be active if auto quest is enabled.
questLimit: 5

# When a quest is completed a leader board message is broadcast. Chose the maximum number of players to be displayed.
# If this is set to 0 then the leader board message will be omitted.
leaderBoardSize: 5

# See color options here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
barColor: "GREEN"

disableBossBar: false

# Should automatic-quest starting be enabled.. If this is enabled, users are not able to start server quests,
# all questing is controlled by the plugin and there will be a timer of randomly selected quests starting every X amount of time.
autoQuest:
    # Should auto quest be enabled
    enabled: true
    # Duration in minutes for which a quest will stay active for.
    duration: 2
    # Delay in minutes between quests. For example quest X starts, after duration X amount of time, the quest ends.
    # Delay is the time between when another quest should start. If this is 0, quests will start, end then start again instantaneously.
    delay: 2

# Placeholder configuration can be configured here.
# Currently, only 1 placeholder exists:
# %quests_message%
# This placeholder will only show valid information when AutoQuest is enabled.
# It takes on two states:
# State 1: When a quest is active
# State 2: When no quests are active
# Each of these states will display information corresponding to the values below.
placeholder:
    questActive: "{QUEST} &a is currently active. {TIME} minutes remaining."
    noQuestsActive: "&7No quests are currently active."

# All quest configuration should be done below. See example quest on spigot page.
Quests:
