# Enabling debug mode will send extra messages in the console log to help debug the plugin.
debug: false

# Number of quests that can be in progress at a time.
# This value is ignored and only 1 quest can be active if auto quest is enabled.
questLimit: 5

# When a quest is completed a leader board message is broadcast. Chose the maximum number of players to be displayed.
# If this is set to 0 then the leader board message will be omitted.
leaderBoardSize: 5

# See color options here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
barColor: "GREEN"

# Pretty straight forward, disables boss bar for quests plugin.
disableBossBar: false

# Configure how rewards should be distributed
rewardDistribution:
    competitive:
        # Sets the mode which rewards should be distributed for competitive quests.
        # Currently only 2 modes:
        # default - default CommunityQuests algorithm (contribution/goal) * (eligible rewards)
        # ranked - rewards are evenly distributed between the top x amount of players (x = benchmark value below)
        mode: ranked
        # Placing benchmark for which players are distributed rewards. For example, a benchmark of 5 would mean
        # the top 5 players who participated in a competitive quest will split a given eligible reward (currently
        # the only eligible rewards are experience, money and BeastTokens)
        benchmark: 5

# Should automatic-quest starting be enabled. If this is enabled, users are not able to start server quests,
# all questing is controlled by the plugin and there will be a timer of randomly selected quests starting every X amount of time.
autoQuest:
    # Should auto quest be enabled
    enabled: true
    # Value used if timeToCompleteCoop value is not set for a given quest.
    defaultDurationCoop: 60
    # Value used if timeToCompleteComp value is not set for a given quest.
    defaultDurationComp: 30
    # Delay in seconds between quests. For example quest X starts, after duration X amount of time, the quest ends.
    # Delay is the time between when another quest should start. If this is 0, quests will start, end then start again instantaneously.
    delay: 120
    # Any quest listed here is exempt from being automatically activated by the AutoQuest algorithm.
    # Example, you have a quest defined as "TestQuest" in the configuration below, if you list it here
    # auto quest will never activate this quest automatically.
    exemptQuests: []

# Placeholder configuration can be configured here.
# Currently, only 1 placeholder exists:
# %quests_message%
# This placeholder will only show valid information when AutoQuest is enabled.
# It takes on two states:
# State 1: When a quest is active
# State 2: When no quests are active
# Each of these states will display information corresponding to the values below.
placeholder:
    questActive: "{QUEST} &a is currently active. {TIME} second(s) remaining."
    noQuestsActive: "&7No quests are currently active."

# All quest configuration should be done below. See example quest on spigot page.
#Quests:
#    TestQuest: # Quest identifier can be whatever you'd like as long as it's unique
#        displayName: '&c&lZombie and Pig Slayer'
#        type: mobkill # required, see type list for available types
#        entities: # This is an optional parameter, if it doesn't exist the quest will count all mob kills. entity reference: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
#            - Zombie
#            - Pig
#            - Pig_Zombie
#        description:
#            - '&4Kill 5 zombies as fast as you can!'
#            - '&6Test test test'
#        timeToCompleteCoop: 30
#        timeToCompleteComp: 20
#        goal: 5 # The goal is the amount of the task to be completed
#        rewards:
#            experience: 100
#            money: 1000 (You must have Vault and an Economy plugin installed for this to work)
#            tokens: 1000 (You must have BeastTokens installed for this to work)
#            items:
#                - material: DIAMOND_SWORD
#                  amount: 1
#                  displayName: '&bPowerful Diamond Sword'
#                - material: APPLE
#                  amount: 12
#                  displayName: '&capples'
