name: TownyQuests
version: ${project.version}
author: wonka01, knighthat, modify
main: me.wonka01.ServerQuests.ServerQuests
api-version: 1.13

commands:
  townyquests:
      aliases: [tq, quests, townyq, tquest, tquests]
      description: Commands for TownyQuests plugin.

softdepend:
    - Vault
    - PlaceholderAPI
    - BeastTokens

permissions:
  townyquests.start:
    description: The ability to start server events
    default: op
  townyquests.stop:
    description: The ability to stop an event
    default: op
  townyquests.reload:
    description: Can reload the plugins configurations
    default: op
  townyquests.view:
    description: Can view all active quests for the server
    default: true
  townyquests.donate:
    description: Can use the donate command to participate in quests
    default: true
  townyquests.money:
      description: Can use the command to contribute money to money quests
      default: true
  townyquests.showmessages:
    description: If true the player will receive a message when they contribute to the quest
    default: false
  townyquests.bossbar.hide:
    description: The player will not be shown the boss bar by default
    default: false
